openapi: 3.0.0
info:
  title: Products
  description: This is the OpenAPI for the Union Fashion product catalog.
  version: '1.0'
servers:
  - url: '{{baseUrl}}'
paths:
  /productss:
    post:
      summary: Add Product  
      responses:
        '201':
          description: Successful creation of product.        
  /products:
    post:
      summary: Add Product
      description: Creates a new productz.
      operationId: addProduct
      tags:
        - Products
      requestBody:
        description: A product schema.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              category: Jeans
              brand: Union
              color: black
              gender: m
              unitPrice: 49.99
              unitSalePrice: 29.99
      security:
        - api_key: []
      responses:
        '201':
          description: Successful creation of product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                status: success
      deprecated: false
    get:
      summary: Get Products
      description: Pulls a list of all product
      operationId: getProducts
      tags:
        - Products
      parameters:
        - name: query
          in: query
          description: A query to search for products by.
          required: true
          schema:
            type: string
            example: shirts
      security:
        - api_key: []
      responses:
        '200':
          description: List of products.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
              example:
                status: success
      deprecated: false
  '/products/{productId}':
    get:
      summary: Get Product
      description: Retrieves a single product.
      operationId: getProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: The product ID to retrieve.
          required: true
          schema:
            type: string
            example: product-one
      responses:
        '200':
          description: Single product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                status: success
      deprecated: false
      security:
        - api_key: []
    put:
      summary: Update
      description: Supports either full or partial updates.
      operationId: updateProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: The product ID to retrieve.
          required: true
          schema:
            type: string
            example: product-one
      security:
        - api_key: []
      requestBody:
        description: A product object.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              unitSalePrice: 29.99
        required: true
      responses:
        '204':
          description: Successfully updated.
      deprecated: false
    delete:
      tags:
        - Products
      summary: Delete
      description: Delete an individual product.
      operationId: deleteProduct
      parameters:
        - name: productId
          in: path
          description: The product ID to retrieve.
          required: true
          schema:
            type: string
            example: product-one
      security:
        - api_key: []
      responses:
        '204':
          description: Product deleted.
      deprecated: false
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
  schemas:
    Products:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    Product:
      title: Product
      required:
        - identifier
        - name
      type: object
      properties:
        identifier:
          type: string
        name:
          type: string
        description:
          type: string
        image:
          type: string
        url:
          type: string
        brand:
          type: string
        category:
          type: string
        color:
          type: string
        logo:
          type: string
        manufacturer:
          type: string
        material:
          type: string
        model:
          type: string
        releaseDate:
          type: string
        sku:
          type: string
        width:
          type: string
        weight:
          type: string
        depth:
          type: string
        height:
          type: string
      example:
        id: XYZ-JEAN-123
        category: Jeans
        brand: Union
        color: black
        gender: m
        unitPrice: 49.99
        unitSalePrice: 29.99
tags:
  - name: Products
    description: A product object.
